package org.jax.mgi.searchtool_wi.matches;

// standard java classes
import java.util.*;
import java.io.IOException;

// lucene
import org.apache.lucene.search.Hit;

// QS shared classes
import org.jax.mgi.shr.searchtool.IndexConstants;

// MGI Shared Classes
import org.jax.mgi.shr.config.Configuration;
import org.jax.mgi.shr.timing.TimeStamper;


/**
* A VocabMatchFactory is responsible for VocabMatch object creation and
*  data initialization
*/
public class VocabMatchFactory extends AbstractMatchFactory
{

  //-------------//
  // Constructor //
  //-------------//

  /**
  * Constructs the factory, calling the parent class constructor with config
  */
  public VocabMatchFactory(Configuration c)
  {
    super(c);
  }

  //------------------------------------//
  // Over-ridden Parent Abstract Method
  //------------------------------------//

  /**
  * Generates and initializes a VocabMatch
  */
  public VocabMatch getMatch(Hit h)
    throws IOException
  {
    // match type generated by this factory
    VocabMatch vocabMatch = new VocabMatch();

    // use parent class's implementation to fill basic information about match
    this.setHit(h);
    this.loadAbstractMatchInfo(vocabMatch);

    // fill data specific to this match type
    vocabMatch.setVocabulary( hit.get(IndexConstants.COL_VOCABULARY) );

    return vocabMatch;

  }

}

